/* ═══════════════════════ SITEMAP GENERATOR ═══════════════════════
   public/sitemap.xml used to be hand-written, with a lastmod hardcoded to
   whichever day someone last remembered to touch it. A test in App.test.js
   caught routes going missing from it, but nothing could catch the date being
   a fiction, and every new route was a second edit waiting to be forgotten.

   Generated from src/routeMeta.mjs — the same table that drives the router,
   the runtime <head>, and the prerendered documents — it cannot drift.

   Emits <loc> and <lastmod> only. Google has said plainly that it ignores
   <priority> and <changefreq>, so the forty lines carrying them said nothing.

   Writes public/, not build/: CRA copies public/ into the build output, and
   keeping the generated file committed is what lets the route-parity test
   read it without running a production build first.

   Run: node scripts/gen-sitemap.mjs   (wired into `npm run build`)
═══════════════════════════════════════════════════════════════════ */
import { writeFileSync, statSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";
import {
  SITE_URL,
  STATIC_ROUTE_META,
  PRIVATE_PATHS,
  DEFAULT_META,
  alternatesFor,
} from "../src/routeMeta.mjs";

/* Last time the page copy actually changed, as a date rather than a timestamp.
   Answer engines weight recency, but a date that moves on every deploy is a
   freshness signal with no freshness behind it, and Google treats that as the
   spam pattern it is. routeMeta.mjs holds every word of every page, so its
   last commit is the honest answer. Falls back to file mtime outside a git
   checkout; Vercel builds from a real clone, so the git path is the one that
   runs in production. */
export const CONTENT_SOURCE = new URL("../src/routeMeta.mjs", import.meta.url).pathname;
/* The translations are page copy too. Left out, editing a German page would
   leave lastmod and dateModified pointing at whenever routeMeta.mjs last
   changed — a freshness signal that misses the edit that actually happened. */
const LOCALE_SOURCE = new URL("../src/locales/", import.meta.url).pathname;
const CONTENT_SOURCES = [CONTENT_SOURCE, LOCALE_SOURCE];

export const contentModified = () => {
  try {
    const iso = execFileSync("git", ["log", "-1", "--format=%cI", "--", ...CONTENT_SOURCES], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (iso) return iso.slice(0, 10);
  } catch {
    /* Not a git checkout, or git is unavailable. Fall through to mtime. */
  }
  return statSync(CONTENT_SOURCE).mtime.toISOString().slice(0, 10);
};

export const sitemapPaths = () =>
  ["/", ...Object.keys(STATIC_ROUTE_META)].filter((p) => !PRIVATE_PATHS.includes(p));

/* Only writes when invoked directly, so prerender.mjs can import the helpers
   above without a second file landing on disk as a side effect. */
if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split("/").pop())) {
  const lastmod = contentModified();
  const paths = sitemapPaths();
  /* Sitemap alternates as well as the <head> tags. Both are valid hreflang
     signals; Search Console's International Targeting report reads the sitemap
     form, which is what makes a missing return link visible rather than silent. */
  const alternatesXml = (p) => {
    const meta = p === "/" ? DEFAULT_META : STATIC_ROUTE_META[p];
    return alternatesFor(meta?.basePath)
      .map((a) => `\n    <xhtml:link rel="alternate" hreflang="${a.hreflang}" href="${a.url}" />`)
      .join("");
  };
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen-sitemap.mjs from src/routeMeta.mjs. Do not edit. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${paths
  .map(
    (p) =>
      `  <url>\n    <loc>${SITE_URL}${p}</loc>\n    <lastmod>${lastmod}</lastmod>${alternatesXml(p)}\n  </url>`,
  )
  .join("\n")}
</urlset>
`;
  writeFileSync(join("public", "sitemap.xml"), xml);
  console.log(`sitemap: ${paths.length} URLs, lastmod ${lastmod}`);
}
